# Generated by Django 5.1.7 on 2025-03-08 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('profiilipilt', models.ImageField(blank=True, null=True, upload_to='disainerid/')),
                ('kasutaja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kollektsioon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100)),
                ('kirjeldus', models.TextField()),
                ('disainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galerii.disainer')),
            ],
        ),
        migrations.CreateModel(
            name='Toode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100)),
                ('kirjeldus', models.TextField()),
                ('hind', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pilt', models.ImageField(upload_to='tooted/')),
                ('pilt_360', models.FileField(blank=True, null=True, upload_to='tooted/360/')),
                ('saadaval', models.BooleanField(default=True)),
                ('kollektsioon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galerii.kollektsioon')),
            ],
        ),
    ]
